### PR TITLE
Album Filtering And Column Sorting

### PR DESCRIPTION
**Pull request by hunoz**
## Description
* Added multiselect dropdown to allow users to select one or more albums
* Each column now has its own sorting based off of the album name, with numbers coming first

## Testing
* Selected multiple albums and verified only those albums showed up
* Selected no albums and verified default view of all albums showed up
* Verified alphabetic accuracy for album name sorting
* Verified items in each column match what is currently in prod
* Verified colors matched as before (please double check as it is possible I missed an incorrect color)

### CODE REVIEW

**Comment by hunoz** [comment]
Note: This is the same as https://github.com/bunceandbean/eras-tour-surprise-songs/pull/1, but I accidentally deleted the fork, causing it to close the PR.

**Comment by bunceandbean** [comment]
Hey there! Thanks for contributing, it means a lot and this is the first time I've ever gotten a PR! I am currently busy with some internship related matters, but I should be able to take a look at this and merge it in sometime this week!

**Comment by hunoz** [comment]
No worries, I saw your post on the subreddit and really like the idea!

**Comment by bunceandbean** [comment]
I like the addition! If you could make its size line up with the other cards and maybe make it a bit smaller on mobile view I'll go ahead and merge it in! Thanks for contributing :)

**Comment by hunoz** [comment]
Continued in https://github.com/bunceandbean/eras-tour-surprise-songs/pull/3 because I am awful at understanding GitHub forks.

**Pull request closed without merging**
